# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/mfaizan/isp_rtl/Sha256_Hw_Accelerator/Sha256_Hw_Accelerator/syn/top.srcs/sources_1/bd/top/ip/top_ps7_0/top_ps7_0.xci
# IP: The module: 'top_ps7_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/mfaizan/isp_rtl/Sha256_Hw_Accelerator/Sha256_Hw_Accelerator/syn/top.srcs/sources_1/bd/top/ip/top_ps7_0/top_ps7_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_ps7_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/mfaizan/isp_rtl/Sha256_Hw_Accelerator/Sha256_Hw_Accelerator/syn/top.srcs/sources_1/bd/top/ip/top_ps7_0/top_ps7_0.xci
# IP: The module: 'top_ps7_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/mfaizan/isp_rtl/Sha256_Hw_Accelerator/Sha256_Hw_Accelerator/syn/top.srcs/sources_1/bd/top/ip/top_ps7_0/top_ps7_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_ps7_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
